### PR TITLE
Fix deprecated calls for KillAdvancement, remove redundant allocations

### LINKED ISSUE #7: KillAdvancement uses a deprecated function call
In file `src/main/java/tv/galaxe/galaxesmp/advancements/KillAdvancement.java` there is a method to get the current item a killer is currently using:

```java
      return Component.text("a " + item.getItemMeta().getDisplayName())
```

The `getDisplayName()` call is deprecated and should be replaced when Minecraft 1.20 releases to avoid pains with migration. It is being replaced with `displayName()`.

### PR DESCRIPTION
**Pull request by garrettsummerfi3ld**
### Information

This PR fixes #7.

### Details

**Proposed fix:**

`KillAdvancement` had a deprecated call that is set for removal soon. This now uses the correct calls to get item display name.

Removed redundant and unused assignments for `TwitchCmd` and `TwitchIntegration`. This threw warnings with Qodana and should now be rectified.

Updates copyright year.

**Environments tested:**

OS: Linux

Java version: 17

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [x] Most recent GeyserMC version (2.XX.Y)

**Demonstration:**

n/a

### CODE REVIEW

**Review by ciph0n — APPROVED** [review]

File: src/main/java/tv/galaxe/galaxesmp/advancements/KillAdvancement.java [hunk 1]
```diff
@@ -1,6 +1,7 @@
-/* (C)2022 GalaxeTV */
+/* (C)2022-2023 GalaxeTV */
```
Comment (yosef022) [inline src/main/java/tv/galaxe/galaxesmp/advancements/KillAdvancement.java:1]: nice balls i mean copyright update

File: src/main/java/tv/galaxe/galaxesmp/commands/TwitchCmd.java [hunk 2]
```diff
@@ -1,4 +1,4 @@
-/* (C)2022 GalaxeTV */
+/* (C)2022-2023 GalaxeTV */
```
Comment (yosef022) [inline src/main/java/tv/galaxe/galaxesmp/commands/TwitchCmd.java:1]: more nice balls

File: src/main/java/tv/galaxe/galaxesmp/util/TwitchIntegration.java [hunk 3]
```diff
@@ -1,4 +1,4 @@
-/* (C)2022 GalaxeTV */
+/* (C)2022-2023 GalaxeTV */
 package tv.galaxe.galaxesmp.util;
```
Comment (yosef022) [inline src/main/java/tv/galaxe/galaxesmp/util/TwitchIntegration.java:2]: it is definitely 2023

**Review by yosef022 — APPROVED** [review]
BOOBIES
